import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AdPlaceholder } from '../components/AdPlaceholder'
import { CategoryCard } from '../components/CategoryCard'
import { Icon } from '../components/Icon'
import { SearchBox } from '../components/SearchBox'
import { SEO, siteUrl } from '../components/SEO'
import { ToolCard } from '../components/ToolCard'
import { categories, getTool, tools } from '../data/registry'

const featuredSlugs=['percentage-calculator','age-calculator','discount-calculator','bmi-calculator','loan-calculator','length-converter','temperature-converter','data-storage-converter']
export function HomePage(){const[query,setQuery]=useState('');const navigate=useNavigate();const submit=(e:React.FormEvent)=>{e.preventDefault();navigate(`/tools${query.trim()?`?q=${encodeURIComponent(query.trim())}`:''}`)};const featured=featuredSlugs.map(getTool).filter(Boolean) as typeof tools
return <><SEO title="ToolNest — Free Online Calculators & Converters" description="Simple, fast and free calculators and converters for math, finance, health, dates and everyday measurements." path="/" jsonLd={{'@context':'https://schema.org','@type':'WebSite',name:'ToolNest',url:siteUrl,potentialAction:{'@type':'SearchAction',target:`${siteUrl}/tools?q={search_term_string}`,'query-input':'required name=search_term_string'}}}/>
<section className="border-b border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"><div className="container-page py-14 sm:py-20"><div className="mx-auto max-w-3xl text-center"><span className="eyebrow">Fast. Private. Free.</span><h1 className="mt-4 text-4xl font-extrabold tracking-[-0.035em] text-ink-950 sm:text-5xl dark:text-white">Everyday tools, all in one place.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-ink-600 dark:text-slate-300">Accurate calculators and converters that work instantly in your browser—without accounts, uploads, or hidden fees.</p><form onSubmit={submit} className="mx-auto mt-8 max-w-2xl"><SearchBox large value={query} onChange={setQuery}/><p className="mt-3 text-xs text-slate-500">Try “percentage”, “age”, “kg”, “loan” or “temperature”</p></form><div className="mt-8 flex flex-wrap justify-center gap-x-6 gap-y-2 text-sm font-semibold text-ink-600 dark:text-slate-300"><span className="inline-flex items-center gap-2"><Icon name="check" className="text-mint-600" size={17}/>No sign-up</span><span className="inline-flex items-center gap-2"><Icon name="check" className="text-mint-600" size={17}/>Works locally</span><span className="inline-flex items-center gap-2"><Icon name="check" className="text-mint-600" size={17}/>{tools.length} useful tools</span></div></div></div></section>
<main><section className="container-page py-12 sm:py-16"><div className="flex items-end justify-between gap-4"><div><span className="eyebrow">Browse by category</span><h2 className="mt-2 text-2xl font-extrabold tracking-tight sm:text-3xl">Find the right tool faster</h2></div><button onClick={()=>navigate('/tools')} className="hidden items-center gap-2 text-sm font-bold text-brand-600 sm:flex">View all <Icon name="arrow" size={17}/></button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.slice(0,5).map(category=><CategoryCard key={category.slug} category={category}/>)}</div></section>
<AdPlaceholder className="my-2"/>
<section className="container-page py-14 sm:py-16"><div><span className="eyebrow">Popular now</span><h2 className="mt-2 text-2xl font-extrabold tracking-tight sm:text-3xl">Popular free tools</h2><p className="mt-3 text-ink-600 dark:text-slate-300">Quick answers for the calculations people use every day.</p></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{featured.map(tool=><ToolCard key={tool.slug} tool={tool}/>)}</div><div className="mt-8 text-center"><button onClick={()=>navigate('/tools')} className="btn-secondary">Explore all {tools.length} tools <Icon name="arrow" size={17}/></button></div></section>
<section className="border-y border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900/40"><div className="container-page grid gap-8 py-14 md:grid-cols-3"><div><span className="grid h-10 w-10 place-items-center rounded-xl bg-mint-50 text-mint-600 dark:bg-mint-600/10"><Icon name="check"/></span><h2 className="mt-4 font-bold">Clear, checked formulas</h2><p className="mt-2 text-sm leading-6 text-ink-600 dark:text-slate-400">Each result includes the method or conversion behind it, so the answer is easy to understand.</p></div><div><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-700/20 dark:text-brand-100"><Icon name="monitor"/></span><h2 className="mt-4 font-bold">Private by design</h2><p className="mt-2 text-sm leading-6 text-ink-600 dark:text-slate-400">Calculations happen on your device. Values are not sent to a calculation service.</p></div><div><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600 dark:bg-amber-600/10 dark:text-amber-300"><Icon name="sparkles"/></span><h2 className="mt-4 font-bold">Built for any screen</h2><p className="mt-2 text-sm leading-6 text-ink-600 dark:text-slate-400">Fast, accessible controls work from a small phone to a full desktop.</p></div></div></section></main></>}
