import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Breadcrumbs } from '../components/Breadcrumbs'
import { SearchBox } from '../components/SearchBox'
import { SEO } from '../components/SEO'
import { ToolCard } from '../components/ToolCard'
import { categories, searchTools, tools } from '../data/registry'

export function ToolsPage(){const[params,setParams]=useSearchParams();const[query,setQuery]=useState(params.get('q')||'');const[category,setCategory]=useState(params.get('category')||'All Tools');useEffect(()=>{const next=new URLSearchParams();if(query.trim())next.set('q',query);if(category!=='All Tools')next.set('category',category);setParams(next,{replace:true})},[query,category,setParams]);const results=searchTools(query,category)
return <main className="container-page py-8 sm:py-12"><SEO title="Free Online Tools — Calculators & Converters | ToolNest" description="Browse all free ToolNest calculators and converters. Search math, finance, health, date, time and measurement tools." path="/tools"/><Breadcrumbs items={[{label:'Home',to:'/'},{label:'Tools'}]}/><div className="max-w-3xl"><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">Free Online Tools</h1><p className="mt-3 text-lg leading-7 text-ink-600 dark:text-slate-300">Simple, fast and free calculators and converters for everyday use.</p></div><div className="card mt-8 p-4 sm:p-5"><SearchBox large value={query} onChange={setQuery} autoFocus={Boolean(params.get('q'))}/><div className="mt-4 flex gap-2 overflow-x-auto pb-1" aria-label="Filter tools by category"><button onClick={()=>setCategory('All Tools')} className={`min-h-10 shrink-0 rounded-full px-4 text-sm font-bold ${category==='All Tools'?'bg-brand-600 text-white':'border bg-white text-ink-600 dark:bg-slate-900 dark:text-slate-300'}`}>All Tools</button>{categories.slice(0,5).map(item=><button key={item.slug} onClick={()=>setCategory(item.name)} className={`min-h-10 shrink-0 rounded-full px-4 text-sm font-bold ${category===item.name?'bg-brand-600 text-white':'border bg-white text-ink-600 dark:bg-slate-900 dark:text-slate-300'}`}>{item.name}</button>)}</div></div><div className="mt-8 flex items-center justify-between gap-4"><p className="text-sm font-semibold text-slate-500" aria-live="polite">{results.length} {results.length===1?'tool':'tools'} found</p>{category!=='All Tools'&&<Link to={`/category/${categories.find(item=>item.name===category)?.slug}`} className="text-sm font-bold text-brand-600">View category page</Link>}</div>{results.length?<div className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{results.map(tool=><ToolCard key={tool.slug} tool={tool}/>)}</div>:<div className="card mt-4 py-16 text-center"><h2 className="text-lg font-bold">No matching tools</h2><p className="mt-2 text-sm text-slate-500">Try a broader term or choose All Tools.</p><button className="btn-secondary mt-5" onClick={()=>{setQuery('');setCategory('All Tools')}}>Clear filters</button></div>}<p className="mt-10 text-center text-xs text-slate-500">All {tools.length} tools work in your browser. No account or external calculation API is used.</p></main>}
