import { lazy, Suspense } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { AdPlaceholder } from '../components/AdPlaceholder'
import { Breadcrumbs } from '../components/Breadcrumbs'
import { Icon } from '../components/Icon'
import { SEO, siteUrl } from '../components/SEO'
import { getCategoryForTool, getTool } from '../data/registry'
import type { ToolGroup } from '../types/tool'

const calculators:Record<ToolGroup,React.LazyExoticComponent<React.ComponentType<{slug:string}>>>={
  math:lazy(()=>import('../calculators/MathTools')),
  finance:lazy(()=>import('../calculators/FinanceTools')),
  health:lazy(()=>import('../calculators/HealthTools')),
  'date-time':lazy(()=>import('../calculators/DateTimeTools')),
  converters:lazy(()=>import('../calculators/ConverterTools')),
}

export function ToolPage(){const{slug=''}=useParams();const tool=getTool(slug);if(!tool)return <Navigate to="/404" replace/>;const category=getCategoryForTool(tool);const Calculator=calculators[tool.group];const related=tool.related.map(getTool).filter(Boolean);const jsonLd=[{'@context':'https://schema.org','@type':'WebApplication',name:tool.name,description:tool.seoDescription,url:`${siteUrl}/tool/${tool.slug}`,applicationCategory:'UtilitiesApplication',operatingSystem:'Any',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'},isAccessibleForFree:true},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{ '@type':'ListItem',position:1,name:'Home',item:siteUrl},{'@type':'ListItem',position:2,name:'Tools',item:`${siteUrl}/tools`},{'@type':'ListItem',position:3,name:category.name,item:`${siteUrl}/category/${category.slug}`},{'@type':'ListItem',position:4,name:tool.name,item:`${siteUrl}/tool/${tool.slug}`}]},{'@context':'https://schema.org','@type':'FAQPage',mainEntity:tool.faqs.map(faq=>({'@type':'Question',name:faq.q,acceptedAnswer:{'@type':'Answer',text:faq.a}}))}]
return <main><SEO title={tool.seoTitle} description={tool.seoDescription} path={`/tool/${tool.slug}`} jsonLd={jsonLd}/><div className="container-page py-8 sm:py-12"><Breadcrumbs items={[{label:'Home',to:'/'},{label:'Tools',to:'/tools'},{label:category.name,to:`/category/${category.slug}`},{label:tool.name}]}/><div className="max-w-3xl"><div className="flex items-center gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-brand-50 text-brand-600 dark:bg-brand-700/20 dark:text-brand-100"><Icon name={tool.icon} size={25}/></span><span className="eyebrow">{tool.category}</span></div><h1 className="mt-5 text-3xl font-extrabold tracking-[-0.025em] sm:text-4xl">{tool.name}</h1><p className="mt-4 text-lg leading-8 text-ink-600 dark:text-slate-300">{tool.intro}</p></div><section aria-labelledby="calculator-heading" className="mt-8 max-w-4xl"><h2 id="calculator-heading" className="sr-only">{tool.name} tool</h2><Suspense fallback={<div className="card min-h-80 animate-pulse p-7" aria-label="Loading calculator"><div className="h-5 w-40 rounded bg-slate-200 dark:bg-slate-800"/><div className="mt-8 h-12 rounded bg-slate-100 dark:bg-slate-800"/><div className="mt-5 h-12 rounded bg-slate-100 dark:bg-slate-800"/></div>}><Calculator slug={tool.slug}/></Suspense></section></div>
<AdPlaceholder className="my-2 sm:my-5"/>
<article className="container-page"><div className="prose-tool max-w-4xl py-8 sm:py-12"><section><h2>Formula</h2><div className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 font-mono text-sm leading-7 text-ink-800 shadow-sm dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200">{tool.formula}</div></section><section><h2>How it works</h2><p>{tool.howItWorks}</p></section>
<AdPlaceholder className="my-10"/>
<section><h2>Examples</h2><ul className="mt-4 grid gap-3">{tool.examples.map((example,index)=><li key={example} className="flex gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm leading-6 text-ink-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-mint-50 text-xs font-extrabold text-mint-600 dark:bg-mint-600/10">{index+1}</span><span>{example}</span></li>)}</ul></section><section><h2>Frequently asked questions</h2><div className="mt-4 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white px-5 dark:divide-slate-800 dark:border-slate-800 dark:bg-slate-900">{tool.faqs.map((faq,index)=><details key={faq.q} className="group py-4" open={index===0}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-ink-950 dark:text-white">{faq.q}<span className="text-xl font-normal text-slate-400 group-open:rotate-45" aria-hidden="true">+</span></summary><p className="mt-3 pr-6 text-sm leading-6 text-ink-600 dark:text-slate-300">{faq.a}</p></details>)}</div></section><section><h2>Related tools</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{related.map(item=><Link key={item!.slug} to={`/tool/${item!.slug}`} className="group flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 font-bold hover:border-brand-100 hover:text-brand-700 dark:border-slate-800 dark:bg-slate-900 dark:hover:border-brand-700 dark:hover:text-brand-100"><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-ink-600 dark:bg-slate-800 dark:text-slate-300"><Icon name={item!.icon} size={18}/></span><span>{item!.name}</span><Icon name="arrow" size={17} className="ml-auto text-slate-400 transition-transform group-hover:translate-x-1"/></Link>)}</div></section></div></article><AdPlaceholder className="mb-4"/></main>}
