import { useState } from 'react'
import { CalculatorFrame } from '../components/CalculatorFrame'
import { DateField, DateTimeField, NumberField, SelectField, TimeField, Toggle } from '../components/Fields'
import { ResultGrid, ResultValue } from '../components/ResultValue'
import { addClamped, addDateParts, ageDifference, calendarDifference, formatDateISO, parseDateOnly, timeDuration } from '../utils/calculations'
import { formatNumber, parseFinite } from '../utils/format'
import type { CalculatorProps } from './types'

function todayISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function prettyDate(date:Date){return new Intl.DateTimeFormat('en-US',{timeZone:'UTC',weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(date)}

function AgeCalculator(){const[birth,setBirth]=useState('2000-05-10'),[target,setTarget]=useState(todayISO());const[result,setResult]=useState<ReturnType<typeof ageDifference>&{nextBirthday:number}|null>(null);const[error,setError]=useState('');const calculate=()=>{try{const b=parseDateOnly(birth),t=parseDateOnly(target);if(!b||!t)throw new Error('Choose a valid date of birth and target date.');if(b>t)throw new Error('Date of birth cannot be after the target date.');const diff=ageDifference(b,t);let next=addClamped(b,diff.years+1,0);if(next<=t)next=addClamped(b,diff.years+2,0);setResult({...diff,nextBirthday:Math.round((next.getTime()-t.getTime())/86400000)});setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setBirth('2000-05-10');setTarget(todayISO());setResult(null);setError('')};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<><ResultValue value={`${result.years} years, ${result.months} months, ${result.days} days`}/><div className="mt-4"><ResultGrid items={[{label:'Total days lived to target',value:formatNumber(result.totalDays)},{label:'Next birthday in',value:`${result.nextBirthday} day${result.nextBirthday===1?'':'s'}`} ]}/></div></>} resultText={result?`${result.years} years, ${result.months} months, ${result.days} days`:''} formula={result?`${birth} to ${target} = ${formatNumber(result.totalDays)} elapsed days`:undefined}><div className="grid gap-5 sm:grid-cols-2"><DateField label="Date of birth" value={birth} max={target} onChange={e=>setBirth(e.target.value)}/><DateField label="Age on date" value={target} min={birth} onChange={e=>setTarget(e.target.value)}/></div></CalculatorFrame>}

function DateDifferenceCalculator(){const[start,setStart]=useState(todayISO()),[end,setEnd]=useState(()=>formatDateISO(addClamped(parseDateOnly(todayISO())!,0,1)));const[result,setResult]=useState<ReturnType<typeof calendarDifference>|null>(null);const[error,setError]=useState('');const calculate=()=>{try{const a=parseDateOnly(start),b=parseDateOnly(end);if(!a||!b)throw new Error('Choose two valid dates.');setResult(calendarDifference(a,b));setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setStart(todayISO());setEnd(formatDateISO(addClamped(parseDateOnly(todayISO())!,0,1)));setResult(null);setError('')};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<><ResultValue value={`${result.years} years, ${result.months} months, ${result.days} days`} detail={result.reversed?'The second date is earlier; the absolute difference is shown.':'Elapsed calendar difference'}/><div className="mt-4"><ResultGrid items={[{label:'Total elapsed days',value:formatNumber(result.totalDays),highlight:true},{label:'Complete weeks',value:`${formatNumber(result.weeks)} weeks + ${result.remainingWeekDays} days`} ]}/></div></>} resultText={result?`${result.years} years, ${result.months} months, ${result.days} days (${result.totalDays} total days)`:''} formula={result?`Absolute difference between ${start} and ${end} = ${result.totalDays} days`:undefined}><div className="grid gap-5 sm:grid-cols-2"><DateField label="Start date" value={start} onChange={e=>setStart(e.target.value)}/><DateField label="End date" value={end} onChange={e=>setEnd(e.target.value)}/></div></CalculatorFrame>}

function DateCalculator(){const[start,setStart]=useState(todayISO()),[direction,setDirection]=useState<'add'|'subtract'>('add'),[years,setYears]=useState('0'),[months,setMonths]=useState('0'),[weeks,setWeeks]=useState('0'),[days,setDays]=useState('30');const[result,setResult]=useState<Date|null>(null);const[error,setError]=useState('');const calculate=()=>{try{const date=parseDateOnly(start);const vals=[years,months,weeks,days].map(parseFinite);if(!date||vals.some(v=>v===null))throw new Error('Choose a valid date and complete all offsets.');if(vals.some(v=>v!<0||!Number.isInteger(v)))throw new Error('Date offsets must be non-negative whole numbers.');setResult(addDateParts(date,direction==='add'?1:-1,vals[0]!,vals[1]!,vals[2]!,vals[3]!));setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setStart(todayISO());setDirection('add');setYears('0');setMonths('0');setWeeks('0');setDays('30');setResult(null);setError('')};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultValue value={prettyDate(result)} detail={formatDateISO(result)}/>} resultText={result?`${prettyDate(result)} (${formatDateISO(result)})`:''} formula={result?`${start} ${direction==='add'?'+':'−'} ${years}y ${months}mo ${weeks}w ${days}d = ${formatDateISO(result)}`:undefined}><div className="grid gap-5 sm:grid-cols-2"><DateField label="Starting date" value={start} onChange={e=>setStart(e.target.value)}/><SelectField label="Operation" value={direction} onChange={e=>setDirection(e.target.value as typeof direction)} options={[{value:'add',label:'Add time'},{value:'subtract',label:'Subtract time'}]}/></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-4"><NumberField label="Years" min="0" step="1" value={years} onChange={e=>setYears(e.target.value)}/><NumberField label="Months" min="0" step="1" value={months} onChange={e=>setMonths(e.target.value)}/><NumberField label="Weeks" min="0" step="1" value={weeks} onChange={e=>setWeeks(e.target.value)}/><NumberField label="Days" min="0" step="1" value={days} onChange={e=>setDays(e.target.value)}/></div></CalculatorFrame>}

function TimeCalculator(){const[start,setStart]=useState('09:15'),[end,setEnd]=useState('17:45'),[overnight,setOvernight]=useState(true);const[result,setResult]=useState<ReturnType<typeof timeDuration>|null>(null);const[error,setError]=useState('');const calculate=()=>{try{setResult(timeDuration(start,end,overnight));setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setStart('09:15');setEnd('17:45');setOvernight(true);setResult(null);setError('')};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultGrid items={[{label:'Duration',value:`${result.hours} hr ${result.remainingMinutes} min`,highlight:true},{label:'Total minutes',value:formatNumber(result.minutes)},{label:'Decimal hours',value:formatNumber(result.decimalHours,4)}]}/>} resultText={result?`${result.hours} hours ${result.remainingMinutes} minutes`:''} formula={result?`${end} − ${start}${end<start&&overnight?' + 24 hours':''} = ${result.minutes} minutes`:undefined}><div className="grid gap-5 sm:grid-cols-2"><TimeField label="Start time" value={start} onChange={e=>setStart(e.target.value)}/><TimeField label="End time" value={end} onChange={e=>setEnd(e.target.value)}/></div><Toggle id="overnight" label="Treat an earlier end time as the next day" checked={overnight} onChange={setOvernight}/></CalculatorFrame>}

const zones=[
  ['UTC','UTC'],['Asia/Karachi','Karachi (PKT)'],['Asia/Kolkata','Delhi / Mumbai (IST)'],['Asia/Dhaka','Dhaka'],['Asia/Dubai','Dubai'],['Asia/Riyadh','Riyadh'],['Asia/Singapore','Singapore'],['Asia/Hong_Kong','Hong Kong'],['Asia/Shanghai','Beijing / Shanghai'],['Asia/Tokyo','Tokyo'],['Australia/Sydney','Sydney'],['Europe/London','London'],['Europe/Paris','Paris / Berlin'],['Europe/Istanbul','Istanbul'],['Africa/Cairo','Cairo'],['Africa/Johannesburg','Johannesburg'],['America/New_York','New York'],['America/Chicago','Chicago'],['America/Denver','Denver'],['America/Los_Angeles','Los Angeles'],['America/Toronto','Toronto'],['America/Sao_Paulo','São Paulo'],['Pacific/Auckland','Auckland']
].map(([value,label])=>({value,label}))
function localDateTime(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function zonedParts(date:Date,zone:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);const get=(type:string)=>Number(parts.find(p=>p.type===type)?.value);return {year:get('year'),month:get('month'),day:get('day'),hour:get('hour'),minute:get('minute'),second:get('second')}}
function wallTimeToDate(input:string,zone:string){const match=input.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/);if(!match)throw new Error('Choose a valid local date and time.');const desired={year:+match[1],month:+match[2],day:+match[3],hour:+match[4],minute:+match[5],second:0};const desiredStamp=Date.UTC(desired.year,desired.month-1,desired.day,desired.hour,desired.minute);let guess=desiredStamp;for(let i=0;i<5;i++){const p=zonedParts(new Date(guess),zone);const shown=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);const delta=desiredStamp-shown;if(delta===0)break;guess+=delta}const check=zonedParts(new Date(guess),zone);if(check.year!==desired.year||check.month!==desired.month||check.day!==desired.day||check.hour!==desired.hour||check.minute!==desired.minute)throw new Error('That local time does not exist in the source zone, likely because of a daylight-saving clock change.');return new Date(guess)}
function TimeZoneCalculator(){const[input,setInput]=useState(localDateTime()),[from,setFrom]=useState('Asia/Karachi'),[to,setTo]=useState('UTC');const[result,setResult]=useState<{formatted:string;iso:string}|null>(null);const[error,setError]=useState('');const calculate=()=>{try{if(from===to){}const instant=wallTimeToDate(input,from);const formatted=new Intl.DateTimeFormat('en-US',{timeZone:to,weekday:'long',year:'numeric',month:'long',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'long'}).format(instant);setResult({formatted,iso:instant.toISOString()});setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setInput(localDateTime());setFrom('Asia/Karachi');setTo('UTC');setResult(null);setError('')};const swap=()=>{setFrom(to);setTo(from);setResult(null)};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultValue value={result.formatted} detail={`Same instant in UTC: ${result.iso.replace('.000','')}`}/>} resultText={result?.formatted||''} formula={result?`${input.replace('T',' ')} in ${from} → ${to}`:undefined}><DateTimeField label="Local date and time in source zone" value={input} onChange={e=>setInput(e.target.value)}/><div className="grid gap-4 sm:grid-cols-[1fr_auto_1fr] sm:items-end"><SelectField label="From time zone" value={from} onChange={e=>setFrom(e.target.value)} options={zones}/><button type="button" onClick={swap} className="btn-secondary px-4" aria-label="Swap time zones">Swap</button><SelectField label="To time zone" value={to} onChange={e=>setTo(e.target.value)} options={zones}/></div></CalculatorFrame>}

export default function DateTimeTools({slug}:CalculatorProps){if(slug==='age-calculator')return <AgeCalculator/>;if(slug==='date-difference-calculator')return <DateDifferenceCalculator/>;if(slug==='date-calculator')return <DateCalculator/>;if(slug==='time-calculator')return <TimeCalculator/>;return <TimeZoneCalculator/>}
