import { useState } from 'react'
import { CalculatorFrame } from '../components/CalculatorFrame'
import { NumberField, SelectField } from '../components/Fields'
import { ResultGrid } from '../components/ResultValue'
import { bmiCategory, bmiMetric, bmr } from '../utils/calculations'
import { formatNumber, parseFinite } from '../utils/format'
import type { CalculatorProps } from './types'

const toMetric = (system:string, weight:number, height:number, inches:number) => system==='metric' ? {kg:weight,cm:height} : {kg:weight*0.45359237,cm:(height*12+inches)*2.54}

function UnitBodyFields({system,setSystem,weight,setWeight,height,setHeight,inches,setInches}:{system:string;setSystem:(v:string)=>void;weight:string;setWeight:(v:string)=>void;height:string;setHeight:(v:string)=>void;inches:string;setInches:(v:string)=>void}){return <><SelectField label="Unit system" value={system} onChange={e=>setSystem(e.target.value)} options={[{value:'metric',label:'Metric (kg, cm)'},{value:'imperial',label:'Imperial (lb, ft, in)'}]}/><div className="grid gap-5 sm:grid-cols-3"><NumberField label="Weight" min="0" value={weight} suffix={system==='metric'?'kg':'lb'} onChange={e=>setWeight(e.target.value)}/><NumberField label={system==='metric'?'Height':'Height (feet)'} min="0" value={height} suffix={system==='metric'?'cm':'ft'} onChange={e=>setHeight(e.target.value)}/>{system==='imperial'&&<NumberField label="Additional inches" min="0" max="11.99" value={inches} suffix="in" onChange={e=>setInches(e.target.value)}/>}</div></>}

function HealthNote(){return <p className="flex gap-2 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800 dark:bg-amber-950/30 dark:text-amber-200"><span aria-hidden="true">ⓘ</span><span>This is an educational estimate, not medical advice or a diagnosis.</span></p>}

function BMICalculator(){const[system,setSystem]=useState('metric'),[weight,setWeight]=useState('70'),[height,setHeight]=useState('175'),[inches,setInches]=useState('6');const[result,setResult]=useState<{bmi:number;category:string;lower:number;upper:number}|null>(null);const[error,setError]=useState('');const calculate=()=>{try{const w=parseFinite(weight),h=parseFinite(height),i=parseFinite(inches);if(w===null||h===null||(system==='imperial'&&i===null))throw new Error('Enter height and weight.');const metric=toMetric(system,w,h,i||0);const value=bmiMetric(metric.kg,metric.cm);const metres=metric.cm/100;setResult({bmi:value,category:bmiCategory(value),lower:18.5*metres**2,upper:24.9*metres**2});setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setSystem('metric');setWeight('70');setHeight('175');setInches('6');setResult(null);setError('')};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultGrid items={[{label:'BMI',value:formatNumber(result.bmi,1),highlight:true},{label:'Adult category',value:result.category},{label:'Healthy-range weight at this height',value:system==='metric'?`${formatNumber(result.lower,1)}–${formatNumber(result.upper,1)} kg`:`${formatNumber(result.lower/0.45359237,1)}–${formatNumber(result.upper/0.45359237,1)} lb`}]}/>} resultText={result?`BMI: ${formatNumber(result.bmi,1)} (${result.category})`:''} formula={result?`${formatNumber(toMetric(system,Number(weight),Number(height),Number(inches)||0).kg)} kg ÷ height² = ${formatNumber(result.bmi,1)}`:undefined}><UnitBodyFields {...{system,setSystem,weight,setWeight,height,setHeight,inches,setInches}}/><HealthNote/></CalculatorFrame>}

function BMRCalculator(){const[system,setSystem]=useState('metric'),[weight,setWeight]=useState('75'),[height,setHeight]=useState('180'),[inches,setInches]=useState('0'),[age,setAge]=useState('30'),[sex,setSex]=useState<'male'|'female'>('male');const[result,setResult]=useState<number|null>(null);const[error,setError]=useState('');const calculate=()=>{try{const w=parseFinite(weight),h=parseFinite(height),i=parseFinite(inches),a=parseFinite(age);if(w===null||h===null||a===null||(system==='imperial'&&i===null))throw new Error('Complete all fields.');const metric=toMetric(system,w,h,i||0);setResult(bmr(sex,metric.kg,metric.cm,a));setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setSystem('metric');setWeight('75');setHeight('180');setInches('0');setAge('30');setSex('male');setResult(null);setError('')};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result!==null&&<ResultGrid items={[{label:'Estimated BMR',value:`${formatNumber(result,0)} kcal/day`,highlight:true},{label:'Per hour at rest',value:`${formatNumber(result/24,1)} kcal`}]}/>} resultText={result!==null?`Estimated BMR: ${formatNumber(result,0)} kcal/day`:''} formula={result!==null?`Mifflin–St Jeor estimate = ${formatNumber(result,0)} kcal/day`:undefined}><div className="grid gap-5 sm:grid-cols-2"><SelectField label="Biological sex used by equation" value={sex} onChange={e=>setSex(e.target.value as typeof sex)} options={[{value:'male',label:'Male (+5 constant)'},{value:'female',label:'Female (−161 constant)'}]}/><NumberField label="Age" min="1" max="130" value={age} suffix="years" onChange={e=>setAge(e.target.value)}/></div><UnitBodyFields {...{system,setSystem,weight,setWeight,height,setHeight,inches,setInches}}/><HealthNote/></CalculatorFrame>}

const activities=[{value:'1.2',label:'Sedentary — little or no exercise'},{value:'1.375',label:'Light — exercise 1–3 days/week'},{value:'1.55',label:'Moderate — exercise 3–5 days/week'},{value:'1.725',label:'Very active — exercise 6–7 days/week'},{value:'1.9',label:'Extra active — intense daily training'}]
function CalorieCalculator(){const[system,setSystem]=useState('metric'),[weight,setWeight]=useState('75'),[height,setHeight]=useState('180'),[inches,setInches]=useState('0'),[age,setAge]=useState('30'),[sex,setSex]=useState<'male'|'female'>('male'),[activity,setActivity]=useState('1.375');const[result,setResult]=useState<{base:number;tdee:number}|null>(null);const[error,setError]=useState('');const calculate=()=>{try{const w=parseFinite(weight),h=parseFinite(height),i=parseFinite(inches),a=parseFinite(age),factor=parseFinite(activity);if(w===null||h===null||a===null||factor===null||(system==='imperial'&&i===null))throw new Error('Complete all fields.');const metric=toMetric(system,w,h,i||0),base=bmr(sex,metric.kg,metric.cm,a);setResult({base,tdee:base*factor});setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setSystem('metric');setWeight('75');setHeight('180');setInches('0');setAge('30');setSex('male');setActivity('1.375');setResult(null);setError('')};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultGrid items={[{label:'Maintenance estimate',value:`${formatNumber(result.tdee,0)} kcal/day`,highlight:true},{label:'BMR at rest',value:`${formatNumber(result.base,0)} kcal/day`},{label:'Moderate deficit reference',value:`${formatNumber(Math.max(1200,result.tdee-500),0)} kcal/day`},{label:'Moderate surplus reference',value:`${formatNumber(result.tdee+300,0)} kcal/day`}]}/>} resultText={result?`Estimated maintenance calories: ${formatNumber(result.tdee,0)} kcal/day`:''} formula={result?`${formatNumber(result.base,0)} BMR × ${activity} activity factor = ${formatNumber(result.tdee,0)} kcal/day`:undefined}><div className="grid gap-5 sm:grid-cols-2"><SelectField label="Biological sex used by equation" value={sex} onChange={e=>setSex(e.target.value as typeof sex)} options={[{value:'male',label:'Male (+5 constant)'},{value:'female',label:'Female (−161 constant)'}]}/><NumberField label="Age" min="1" max="130" value={age} suffix="years" onChange={e=>setAge(e.target.value)}/></div><UnitBodyFields {...{system,setSystem,weight,setWeight,height,setHeight,inches,setInches}}/><SelectField label="Typical activity level" value={activity} onChange={e=>setActivity(e.target.value)} options={activities}/><HealthNote/></CalculatorFrame>}

export default function HealthTools({slug}:CalculatorProps){if(slug==='bmi-calculator')return <BMICalculator/>;if(slug==='bmr-calculator')return <BMRCalculator/>;return <CalorieCalculator/>}
