import { useState } from 'react'
import { CalculatorFrame } from '../components/CalculatorFrame'
import { NumberField, SelectField, TextAreaField } from '../components/Fields'
import { ResultGrid, ResultValue } from '../components/ResultValue'
import { applyPercentageChange, average, calculateFraction, percentageDecrease, percentageIncrease, percentageOf, percentIs, simplifyRatio } from '../utils/calculations'
import { formatNumber, parseFinite, parseNumberList } from '../utils/format'
import type { CalculatorProps } from './types'

function PercentageCalculator() {
  const [mode, setMode] = useState('of')
  const [a, setA] = useState('25'); const [b, setB] = useState('200')
  const [result, setResult] = useState<{ value: number; formula: string } | null>(null); const [error, setError] = useState('')
  const calculate = () => { try { const x=parseFinite(a), y=parseFinite(b); if(x===null||y===null) throw new Error('Enter both values.'); let value:number; let formula:string
    if(mode==='of'){value=percentageOf(x,y);formula=`${formatNumber(x)} ÷ 100 × ${formatNumber(y)} = ${formatNumber(value)}`}
    else if(mode==='is'){value=percentIs(x,y);formula=`${formatNumber(x)} ÷ ${formatNumber(y)} × 100 = ${formatNumber(value)}%`}
    else {value=applyPercentageChange(x,y,mode==='increase'?'increase':'decrease');formula=`${formatNumber(x)} × (1 ${mode==='increase'?'+':'−'} ${formatNumber(y)} ÷ 100) = ${formatNumber(value)}`}
    setResult({value,formula});setError('') } catch(e){setResult(null);setError((e as Error).message)} }
  const reset=()=>{setMode('of');setA('25');setB('200');setResult(null);setError('')}
  const aLabel=mode==='of'?'Percentage':mode==='is'?'Part value':'Starting value'; const bLabel=mode==='of'?'Whole value':mode==='is'?'Whole value':'Change percentage'
  return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultValue value={`${formatNumber(result.value)}${mode==='is'?'%':''}`}/>} resultText={result?`${formatNumber(result.value)}${mode==='is'?'%':''}`:''} formula={result?.formula}>
    <SelectField label="Calculation" value={mode} onChange={e=>{setMode(e.target.value);setResult(null)}} options={[{value:'of',label:'What is X% of Y?'},{value:'is',label:'X is what percent of Y?'},{value:'increase',label:'Increase X by Y%'},{value:'decrease',label:'Decrease X by Y%'}]}/>
    <div className="grid gap-5 sm:grid-cols-2"><NumberField label={aLabel} value={a} onChange={e=>setA(e.target.value)} suffix={mode==='of'?'%':undefined}/><NumberField label={bLabel} value={b} onChange={e=>setB(e.target.value)} suffix={mode==='increase'||mode==='decrease'?'%':undefined}/></div>
  </CalculatorFrame>
}

function ChangeCalculator({ decrease=false }: { decrease?: boolean }) {
  const [original,setOriginal]=useState(decrease?'250':'80'); const [next,setNext]=useState(decrease?'200':'100'); const [result,setResult]=useState<{percent:number;change:number}|null>(null); const [error,setError]=useState('')
  const calculate=()=>{try{const a=parseFinite(original),b=parseFinite(next);if(a===null||b===null)throw new Error('Enter both values.');const percent=decrease?percentageDecrease(a,b):percentageIncrease(a,b);setResult({percent,change:(decrease?a-b:b-a)});setError('')}catch(e){setResult(null);setError((e as Error).message)}}
  const reset=()=>{setOriginal(decrease?'250':'80');setNext(decrease?'200':'100');setResult(null);setError('')}
  return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultGrid items={[{label:decrease?'Percentage decrease':'Percentage increase',value:`${formatNumber(result.percent)}%`,highlight:true},{label:'Absolute change',value:formatNumber(result.change)}]}/>} resultText={result?`${formatNumber(result.percent)}%`:''} formula={result?`(${original} ${decrease?'−':'→'} ${next}) relative to ${original} = ${formatNumber(result.percent)}%`:undefined}>
    <div className="grid gap-5 sm:grid-cols-2"><NumberField label="Original value" value={original} onChange={e=>setOriginal(e.target.value)}/><NumberField label="New value" value={next} onChange={e=>setNext(e.target.value)}/></div>
  </CalculatorFrame>
}

function FractionCalculator(){
  const [a,setA]=useState('1'),[b,setB]=useState('2'),[c,setC]=useState('1'),[d,setD]=useState('3'),[op,setOp]=useState('+'); const [result,setResult]=useState<ReturnType<typeof calculateFraction>|null>(null);const[error,setError]=useState('')
  const calculate=()=>{try{const values=[a,b,c,d].map(parseFinite);if(values.some(v=>v===null))throw new Error('Complete both fractions.');setResult(calculateFraction(values[0]!,values[1]!,values[2]!,values[3]!,op as '+'|'-'|'×'|'÷'));setError('')}catch(e){setResult(null);setError((e as Error).message)}}
  const reset=()=>{setA('1');setB('2');setC('1');setD('3');setOp('+');setResult(null);setError('')}
  return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultGrid items={[{label:'Simplified fraction',value:result.denominator===1?String(result.numerator):`${result.numerator} / ${result.denominator}`,highlight:true},{label:'Decimal',value:formatNumber(result.decimal)}]}/>} resultText={result?`${result.numerator}/${result.denominator} (${formatNumber(result.decimal)})`:''} formula={result?`${a}/${b} ${op} ${c}/${d} = ${result.numerator}/${result.denominator}`:undefined}>
    <div className="grid grid-cols-[1fr_72px_1fr] items-end gap-3"><div className="grid gap-2"><NumberField label="First numerator" value={a} step="1" onChange={e=>setA(e.target.value)}/><NumberField label="First denominator" value={b} step="1" onChange={e=>setB(e.target.value)}/></div><SelectField label="Operation" value={op} onChange={e=>setOp(e.target.value)} options={['+','-','×','÷'].map(v=>({value:v,label:v}))}/><div className="grid gap-2"><NumberField label="Second numerator" value={c} step="1" onChange={e=>setC(e.target.value)}/><NumberField label="Second denominator" value={d} step="1" onChange={e=>setD(e.target.value)}/></div></div>
  </CalculatorFrame>
}

function RatioCalculator(){const[a,setA]=useState('18'),[b,setB]=useState('24');const[result,setResult]=useState<ReturnType<typeof simplifyRatio>|null>(null);const[error,setError]=useState('');const calculate=()=>{try{const x=parseFinite(a),y=parseFinite(b);if(x===null||y===null)throw new Error('Enter both parts of the ratio.');setResult(simplifyRatio(x,y));setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setA('18');setB('24');setResult(null);setError('')};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultGrid items={[{label:'Simplified ratio',value:`${result.left} : ${result.right}`,highlight:true},{label:'Left ÷ right',value:result.decimal===null?'Undefined (right side is zero)':formatNumber(result.decimal)}]}/>} resultText={result?`${result.left}:${result.right}`:''} formula={result?`${a}:${b} = ${result.left}:${result.right}`:undefined}><div className="grid grid-cols-[1fr_auto_1fr] items-end gap-3"><NumberField label="Left value" value={a} onChange={e=>setA(e.target.value)}/><span className="pb-3 text-xl font-bold text-slate-400">:</span><NumberField label="Right value" value={b} onChange={e=>setB(e.target.value)}/></div></CalculatorFrame>}

function AverageCalculator(){const[values,setValues]=useState('4, 8, 12');const[result,setResult]=useState<ReturnType<typeof average>|null>(null);const[error,setError]=useState('');const calculate=()=>{try{const list=parseNumberList(values);if(!list)throw new Error('Enter valid numbers separated by commas, spaces, or lines.');setResult(average(list));setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setValues('4, 8, 12');setResult(null);setError('')};return <CalculatorFrame onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultGrid items={[{label:'Average (mean)',value:formatNumber(result.mean),highlight:true},{label:'Sum',value:formatNumber(result.sum)},{label:'Count',value:String(result.count)},{label:'Range',value:`${formatNumber(result.min)} to ${formatNumber(result.max)}`}]}/>} resultText={result?`Average: ${formatNumber(result.mean)}`:''} formula={result?`${formatNumber(result.sum)} ÷ ${result.count} = ${formatNumber(result.mean)}`:undefined}><TextAreaField label="Numbers" hint="Separate values with commas, spaces, semicolons, or new lines." value={values} onChange={e=>setValues(e.target.value)} placeholder="4, 8, 12"/></CalculatorFrame>}

function secureRandom(){const data=new Uint32Array(1);crypto.getRandomValues(data);return data[0]/4294967296}
function RandomGenerator(){const[min,setMin]=useState('1'),[max,setMax]=useState('100'),[count,setCount]=useState('1'),[type,setType]=useState('integer'),[places,setPlaces]=useState('2');const[result,setResult]=useState<number[]|null>(null);const[error,setError]=useState('');const calculate=()=>{try{const lo=parseFinite(min),hi=parseFinite(max),qty=parseFinite(count),dp=parseFinite(places);if(lo===null||hi===null||qty===null||dp===null)throw new Error('Complete all settings.');if(lo>=hi)throw new Error('Maximum must be greater than minimum.');if(!Number.isInteger(qty)||qty<1||qty>100)throw new Error('Quantity must be a whole number from 1 to 100.');if(!Number.isInteger(dp)||dp<0||dp>10)throw new Error('Decimal places must be from 0 to 10.');const values=Array.from({length:qty},()=>type==='integer'?Math.floor(secureRandom()*(Math.floor(hi)-Math.ceil(lo)+1))+Math.ceil(lo):Number((lo+secureRandom()*(hi-lo)).toFixed(dp)));setResult(values);setError('')}catch(e){setResult(null);setError((e as Error).message)}};const reset=()=>{setMin('1');setMax('100');setCount('1');setType('integer');setPlaces('2');setResult(null);setError('')};return <CalculatorFrame calculateLabel="Generate" onCalculate={calculate} onReset={reset} error={error} result={result&&<ResultValue value={result.map(formatNumber).join(', ')} detail={`${result.length} random ${type}${result.length===1?'':'s'}`}/>} resultText={result?result.join(', '):''} formula={result?`Cryptographic random values mapped from ${min} to ${max}`:undefined}><div className="grid gap-5 sm:grid-cols-2"><NumberField label="Minimum" value={min} onChange={e=>setMin(e.target.value)}/><NumberField label="Maximum" value={max} onChange={e=>setMax(e.target.value)}/><NumberField label="Quantity" min="1" max="100" step="1" value={count} onChange={e=>setCount(e.target.value)}/><SelectField label="Number type" value={type} onChange={e=>setType(e.target.value)} options={[{value:'integer',label:'Whole numbers'},{value:'decimal',label:'Decimal numbers'}]}/>{type==='decimal'&&<NumberField label="Decimal places" min="0" max="10" step="1" value={places} onChange={e=>setPlaces(e.target.value)}/>}</div></CalculatorFrame>}

export default function MathTools({slug}:CalculatorProps){if(slug==='percentage-calculator')return <PercentageCalculator/>;if(slug==='percentage-increase-calculator')return <ChangeCalculator/>;if(slug==='percentage-decrease-calculator')return <ChangeCalculator decrease/>;if(slug==='fraction-calculator')return <FractionCalculator/>;if(slug==='ratio-calculator')return <RatioCalculator/>;if(slug==='average-calculator')return <AverageCalculator/>;return <RandomGenerator/>}
